DELETE http://localhost:3000/api/v1/tours/64065e4ab921805249527d93
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDZmN2IwMjM5Y2QxMDczNTg3ZmQ5NiIsImlhdCI6MTY3ODE3ODQ2MiwiZXhwIjoxNjc5MDQyNDYyfQ.Gzsmbg3vcnYevogTPKOoYWxzzXHYQ3i5QUwokyP7vSY