GET http://localhost:3000/api/v1/reviews
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGExZTFhMmY4ZmI4MTRiNTZmYTE4MiIsImlhdCI6MTY3ODgyNzYwNSwiZXhwIjoxNjc5NjkxNjA1fQ.f8tsNvQZZaAQOHo3bwFIANl_yA2Iod78fbr6gv1VCBA
