POST http://localhost:3000/api/v1/tours
Content-Type: application/json

{
  "name": "New Testing tour",
  "duration": 3,
  "maxGroupSize": 12,
  "difficulty": "easy",
  "ratingsAverage": 4.9,
  "ratingsQuantity": 33,
  "price": 1497,
  "summary": "Enjoy the Northern Lights in one of the best places in the world",
  "description": "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua, ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum!\nDolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur, exercitation ullamco laboris nisi ut aliquip. Lorem ipsum dolor sit amet, consectetur adipisicing elit!",
  "imageCover": "tour-9-cover.jpg",
  "images": ["tour-9-1.jpg", "tour-9-2.jpg", "tour-9-3.jpg"],
  "startDates": ["2021-12-16,10:00", "2022-01-16,10:00", "2022-12-12,10:00"],
  "guides": [
    "6406f7e4239cd1073587fd98",
    "6406f7b0239cd1073587fd96"
  ]
}