GET http://localhost:3000/api/v1/tours
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDZmN2U0MjM5Y2QxMDczNTg3ZmQ5OCIsImlhdCI6MTY3ODc0MDg3MCwiZXhwIjoxNjc5NjA0ODcwfQ.LaC6m6k-Y_4hILDEft5DpCrHgv_nfFikSCQatDIrHXk