GET http://localhost:3000/api/v1/tours/5c88fa8cf4afda39709c2955/reviews
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDZmN2U0MjM5Y2QxMDczNTg3ZmQ5OCIsImlhdCI6MTY3ODU0MDU4NywiZXhwIjoxNjc5NDA0NTg3fQ.H347_u59mDvo8vBdcq6NHYz8i8syi7IUMxdkQwUKnoQ

//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDZmN2IwMjM5Y2QxMDczNTg3ZmQ5NiIsImlhdCI6MTY3ODcyNzAwNCwiZXhwIjoxNjc5NTkxMDA0fQ.ckBPct3Yw320ofaE3aI9U16166d-tChx0LjF4BexJGE // admin
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDZmN2U0MjM5Y2QxMDczNTg3ZmQ5OCIsImlhdCI6MTY3ODU0MDU4NywiZXhwIjoxNjc5NDA0NTg3fQ.H347_u59mDvo8vBdcq6NHYz8i8syi7IUMxdkQwUKnoQ // user