PATCH http://localhost:3000/api/v1/users/updateMyPassword
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDZmN2U0MjM5Y2QxMDczNTg3ZmQ5OCIsImlhdCI6MTY3ODM2NTY2NywiZXhwIjoxNjc5MjI5NjY3fQ.pPjrmLSc52C4bWjf0XGTmTl6Fqxnmh8A-a2-_jwLxu0

{
    "passwordCurrent": "nabeel@123",
    "password": "nabeelanwar",
    "passwordConfirm": "nabeelanwar"
}