PATCH http://localhost:3000/api/v1/users/resetPassword/e3b4e2c4c04eb1853bb2e381421190b1a7b8acaf75a65f0b7c3014a035528afb
Content-Type: application/json

{
    "password": "nabeel@123",
    "passwordConfirm": "nabeel@123"
}
