POST http://localhost:3000/api/v1/users/signup
Content-Type: application/json

{
    "name": "Test2",
    "email": "nabeel@gmail.com",
    "password": "nabeel@123",
    "passwordConfirm": "nabeel@123",
    "role": "user"
}