DELETE http://localhost:3000/api/v1/users/640f69403bcfdb612ecc31d0
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDZmN2U0MjM5Y2QxMDczNTg3ZmQ5OCIsImlhdCI6MTY3ODM2NzEwMSwiZXhwIjoxNjc5MjMxMTAxfQ.3uQP2CIe7zJ9uTPuxtqlcUlefa0sloN24muUffULw-c